GET http://127.0.0.1:8000/user/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzQ2NjQ0OTg0LCJpYXQiOjE3NDY2NDQ2ODQsImp0aSI6IjdiMjgzMjNiODRjYzQ5ZDdhNWU3OTNmNWEyYzdlNDJiIiwidXNlcl9pZCI6MX0.rEpdc8Tcx5v87kBinxnIlDW0b9XFCMuBNqKzcMTaHkI



### post subject
POST http://127.0.0.1:8000/subject/
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzQ2NzM5NTE0LCJpYXQiOjE3NDY3MzkyMTQsImp0aSI6IjJiN2IxNDM4YWVmNjRiZTRhZTg5MWIyNDlhYmY2YTVhIiwidXNlcl9pZCI6MX0.MnPdy6C8oFNxiletgX5OEqXZf4RPfOynKG1mB_y4U5k


{
    "subject": "omar1"
}

### post Topic
POST http://127.0.0.1:8000/topic/
Content-Type: application/json

{
    "subject": 32,
    "topic": "green"
}


### post tag
POST http://127.0.0.1:8000/tag/
Content-Type: application/json

{
    "tag": "Morning"
}


### log session
POST http://127.0.0.1:8000/log/
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzQ2NzM3NzIxLCJpYXQiOjE3NDY3Mzc0MjEsImp0aSI6ImIxYTBjYTM5ZDkyYTQzZWFiNDMyNWM5MzZlNjRmZTJmIiwidXNlcl9pZCI6MX0.xbWZ9uvEgVFAGtwRqratFCMzYfJoR59Vw9Z5Garrn-M


{
    "duration": "10000",
    "subject": "31",
    "focus": 4
}


### log goal
POST http://127.0.0.1:8000/goal/
Content-Type: application/json

{
    "end": "2024-8-9",
    "minutes": 400
}


### register
POST http://127.0.0.1:8000/register/
Content-Type: application/json

{
    "username": "hi",
    "password": "hi",
    "email": "omar@on.com"
}


###

POST http://127.0.0.1:8000/api/token/
Content-Type: application/json

{
    "username": "omar",
    "password": "omar"
}

