# Generated by Django 5.2 on 2025-05-02 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_goal_user_alter_topic_subject'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='color',
            field=models.CharField(default='#1d5fc2', max_length=16),
        ),
    ]
