# Generated by Django 5.2 on 2025-05-02 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_subject_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subject',
            name='color',
            field=models.CharField(blank=True, default='#1d5fc2', max_length=16),
        ),
    ]
