# Generated by Django 5.2 on 2025-05-02 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_subject_color'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='session',
            name='end',
        ),
        migrations.RemoveField(
            model_name='session',
            name='start',
        ),
        migrations.AddField(
            model_name='session',
            name='duration',
            field=models.IntegerField(default=60),
        ),
    ]
